# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-10 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('school_status', models.CharField(max_length=200)),
                ('profile_image_url', models.CharField(max_length=200)),
                ('further_info_url', models.CharField(blank=True, default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presenter', models.CharField(max_length=200)),
                ('profile_image_url', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=500)),
                ('long_description', models.CharField(max_length=10000)),
                ('description_url', models.CharField(max_length=200)),
                ('supp_url', models.CharField(blank=True, default=None, max_length=200)),
                ('affiliation', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
