# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-13 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IQUISE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=2000)),
                ('default_location', models.CharField(default='MIT Room 26-214', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='presentation',
            name='location',
            field=models.CharField(default='MIT Room 26-214', max_length=200),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='date',
            field=models.DateTimeField(verbose_name='presentation date'),
        ),
    ]
