# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_presentation_affiliation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='supp_url',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
