# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20171030_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('school_status', models.CharField(max_length=200)),
                ('profile_image_url', models.CharField(max_length=200)),
                ('further_info_url', models.CharField(blank=True, default=None, max_length=200)),
            ],
        ),
    ]
