# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-12-13 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_presenter_profile_image_thumb'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddedVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EmbedEngine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('html_template', models.TextField(help_text='Use {{URL}} which will get swapped in for the presentation.video.url.')),
            ],
        ),
        migrations.AlterField(
            model_name='presenter',
            name='profile_image_thumb',
            field=models.ImageField(blank=True, editable=False, upload_to='thumbs'),
        ),
        migrations.AddField(
            model_name='embeddedvideo',
            name='engine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.EmbedEngine'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.EmbeddedVideo'),
        ),
    ]
