# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-06-16 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20191213_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presenter',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to=website.models.photo_path('presenters')),
        ),
        migrations.AlterField(
            model_name='presenter',
            name='profile_image_thumb',
            field=models.ImageField(blank=True, editable=False, upload_to=website.models.photo_path('thumbs')),
        ),
    ]
