# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-12-13 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20191213_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='embedengine',
            name='domain',
            field=models.CharField(default='hello', help_text='Used to verify the EmbeddedVideo is using the correct domain.', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='embedengine',
            name='url_help',
            field=models.CharField(blank=True, help_text='Used to help the user figure out which URL to use for embedding.', max_length=100),
        ),
        migrations.AlterField(
            model_name='embeddedvideo',
            name='engine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.EmbedEngine'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.EmbeddedVideo'),
        ),
    ]
