# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-12-12 18:36
from __future__ import unicode_literals

from django.db import migrations
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20200616_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=website.models.EmailIField(blank=True, help_text='Please use your university email if possible.', max_length=254),
        ),
    ]
