# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-12-13 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20191213_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='embeddedvideo',
            name='url',
        ),
        migrations.RemoveField(
            model_name='embedengine',
            name='domain',
        ),
        migrations.AddField(
            model_name='embeddedvideo',
            name='video_id',
            field=models.CharField(default='abc', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='embedengine',
            name='url_template',
            field=models.CharField(default='abc', help_text='Use {{video_id}} which will get swapped in for the EmbeddedVideo.video_id.', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='embedengine',
            name='url_help',
            field=models.CharField(blank=True, help_text='Used to help the user figure out where the video_id is.', max_length=100),
        ),
    ]
