# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-12-13 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20191213_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='embedengine',
            name='url_template',
        ),
        migrations.AlterField(
            model_name='embedengine',
            name='html_template',
            field=models.TextField(help_text='Use {{ID}} which will get swapped in for the EmbeddedVideo.video_id.'),
        ),
    ]
