# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-12-20 23:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_remove_event_audience'),
    ]

    database_operations = [
        migrations.AlterModelTable('School', 'members_school'),
        migrations.AlterModelTable('Department', 'members_department'),
        migrations.AlterModelTable('Person', 'members_person'),
        migrations.AlterModelTable('Profile', 'members_profile'),
    ]

    state_operations = [
        migrations.DeleteModel('School'),
        migrations.DeleteModel('Department'),
        migrations.DeleteModel('Person'),
        migrations.DeleteModel('Profile'),
    ]

    operations = [
      migrations.SeparateDatabaseAndState(
        database_operations=database_operations,
        state_operations=state_operations)
    ]
