# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-12-20 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('website', '0009_auto_20201220_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='audience',
            field=models.ManyToManyField(blank=True, to='members.Person'),
        ),
    ]
