# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-02-07 02:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_event_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='audience',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
