# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-04-12 14:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import website.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0011_auto_20210206_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=10, unique=True)),
                ('valid_through', models.DateTimeField(default=website.models.tomorrow)),
                ('valid_for_n_uses', models.PositiveIntegerField(default=0, help_text='A value of 0 indicates any number of uses.')),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(default=website.models.get_guest_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
