# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-04-11 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_remake_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='point',
            new_name='rank',
        ),
        migrations.AddField(
            model_name='voter',
            name='has_voted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('voter', 'candidate', 'rank')]),
        ),
    ]
