# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-04-12 14:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elections', '0003_auto_20210411_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='submitted',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='token',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('voter', 'candidate')]),
        ),
        migrations.AlterUniqueTogether(
            name='voter',
            unique_together=set([('election', 'user')]),
        ),
    ]
