# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-04-17 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_auto_20210412_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='nominee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='elections.Nominee'),
        ),
    ]
