# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-25 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='modified_by',
        ),
    ]
