# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-12-20 23:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import members.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("website", "0009_auto_20201220_1811"),
    ]

    state_operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': '\u200b\u200b\u200b\u200b\u200b\u200b\u200bDepartments',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', members.models.EmailIField(blank=True, help_text='Please use your university email if possible.', max_length=254)),
                ('MIT_ID', models.PositiveIntegerField(blank=True, null=True, verbose_name='MIT ID')),
                ('year', models.CharField(blank=True, help_text='Sophomore, Graduate Year #, Postdoc, Professor, etc.', max_length=10)),
                ('lab', models.CharField(blank=True, max_length=200)),
                ('subscribed', models.BooleanField(default=False, help_text='iquise-associates@mit.edu')),
                ('join_method', models.CharField(choices=[('manual', 'Manual Entry'), ('website', 'Requested on Website'), ('moira', 'Joined through Moira'), ('id', 'MIT ID')], default='manual', max_length=20)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Department')),
            ],
            options={
                'ordering': ['-last_name', '-first_name'],
                'verbose_name_plural': '\u200b\u200b\u200b\u200b\u200bPeople',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=200)),
                ('school_status', models.CharField(blank=True, max_length=200)),
                ('profile_image', models.ImageField(blank=True, upload_to='staff_profiles')),
                ('further_info_url', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': '\u200b\u200b\u200b\u200b\u200b\u200bSchools',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.School'),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
