# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-01-11 13:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import functools
import members.models

def make_missing_committees(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Committee = apps.get_model("members", "Committee")
    Position = apps.get_model("members", "Position")
    for group in Group.objects.filter(committee__isnull=True):
        Committee(group=group).save()
        # Default position (can't reference default attrs)
        Position(name="", committee=group, index=32767).save()


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Short description here on first line (next line blank!).<br><br>Elaborate here if you need.<br>Multiple lines if needed.', max_length=500)),
                ('contact_email', models.EmailField(blank=True, help_text="If blank, parent's email will be used if available.", max_length=254)),
                ('show_email', models.BooleanField(default=True, help_text='If no self or parent Contact email; will not be displayed.')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='auth.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('index', models.PositiveSmallIntegerField(default=0, help_text='Order to render on page.')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='auth.Group')),
            ],
            options={
                'ordering': ['committee', 'index'],
            },
        ),
        migrations.CreateModel(
            name='PositionHeld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(default=members.models.get_current_term_start)),
                ('stop', models.DateField(blank=True, null=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Position')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start', 'position'],
                'verbose_name_plural': 'Positions Held',
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(default=functools.partial(members.models.get_current_term_start, *(), **{b'days': 365}), help_text="This term will extend to the next term's start date.")),
            ],
            options={
                'ordering': ['-start'],
            },
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='school_status',
            new_name='affiliation',
        ),
        migrations.RemoveField(
            model_name='person',
            name='MIT_ID',
        ),
        migrations.RemoveField(
            model_name='person',
            name='department',
        ),
        migrations.RemoveField(
            model_name='person',
            name='join_method',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.AddField(
            model_name='position',
            name='users',
            field=models.ManyToManyField(through='members.PositionHeld', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together=set([('committee', 'index'), ('committee', 'name')]),
        ),
        migrations.RunPython(
            code=make_missing_committees,
        ),
    ]
