# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-12-22 01:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='MIT_ID',
        ),
        migrations.RemoveField(
            model_name='person',
            name='department',
        ),
        migrations.RemoveField(
            model_name='person',
            name='join_method',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
