# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-02-07 01:43
from __future__ import unicode_literals
import datetime

from django.db import migrations, models
from django.utils.timezone import utc
import members.models
from iquise.utils import random_password

def move_data(apps, schema_editor):
    EmailList = apps.get_model("members", "EmailList")
    email_list = EmailList(address="iquise-associates@mit.edu")
    email_list.save()

    Person = apps.get_model("members", "Person")
    Profile = apps.get_model("members", "Profile")
    User = apps.get_model("auth", "User")
    CRUDEvent = apps.get_model("easyaudit", "CRUDEvent")
    ContentType = apps.get_model("contenttypes", "ContentType")
    for p in Person.objects.all():
        c_event = CRUDEvent.objects.get(event_type=1, content_type=ContentType.objects.get_for_model(Person), object_id=p.id)
        u = User(
            username=p.email.lower(),
            email=p.email.lower(),
            first_name=p.first_name,
            last_name=p.last_name,
            password=random_password(),
        )
        u.save()
        profile = Profile(
            user=u,
            year=p.year,
            affiliation=p.lab,
            graduation_year=0,
        )
        profile.save()
        if p.subscribed:
            profile.subscriptions.add(email_list)

class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20210111_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', members.models.EmailIField(max_length=254, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='graduation_year',
            field=models.PositiveSmallIntegerField(null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscriptions',
            field=models.ManyToManyField(related_name='subscribers', to='members.EmailList'),
        ),
        migrations.RunPython(
            code=move_data,
        ),
    ]
