# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-12-28 17:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0003_auto_20201227_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionHeld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(default=django.utils.timezone.localdate)),
                ('stop', models.DateField(blank=True, null=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Position')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Positions Held',
            },
        ),
        migrations.RemoveField(
            model_name='committeemembership',
            name='position',
        ),
        migrations.AddField(
            model_name='position',
            name='users',
            field=models.ManyToManyField(through='members.PositionHeld', to=settings.AUTH_USER_MODEL),
        ),
    ]
