# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-04-04 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20210208_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to='members.EmailList'),
        ),
    ]
