# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-08-28 12:53
from __future__ import unicode_literals

from django.db import migrations, models

def make_default_valid_domains(apps, schema_editor):
    ValidEmailDomain = apps.get_model("members", "ValidEmailDomain")
    ValidEmailDomain(domain="edu", status="a").save() # accept
    ValidEmailDomain(domain="gmail.com", status="r").save() # reject
    ValidEmailDomain(domain="yahoo.com", status="r").save() # reject
    ValidEmailDomain(domain="hotmail.com", status="r").save() # reject

def transfer_old_to_new_style_subscription(apps, schema_editor):
    Profile = apps.get_model("members", "Profile")
    EmailList = apps.get_model("members", "EmailList")
    # We will assume all existing accounts should be subscribed to iquise-associates
    # Remember, if they're already subscribed, they won't appear in pending filter
    iquise_associates = EmailList.objects.get(address="iquise-associates@mit.edu")
    for profile in Profile.objects.all():
        profile.subscription_requests.add(iquise_associates)

class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20210404_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidEmailDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('u', 'Unreviewed'), ('a', 'Accepted'), ('d', 'Denied')], default='a', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription_requests',
            field=models.ManyToManyField(blank=True, related_name='_profile_subscription_requests_+', to='members.EmailList'),
        ),
        migrations.RunPython(
            code=make_default_valid_domains,
        ),
        migrations.RunPython(
            code=transfer_old_to_new_style_subscription,
        ),
    ]
