# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-08-28 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20210404_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidEmailDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('u', 'Unreviewed'), ('a', 'Accepted'), ('d', 'Denied')], default='a', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription_requests',
            field=models.ManyToManyField(blank=True, related_name='_profile_subscription_requests_+', to='members.EmailList'),
        ),
    ]
