# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-12-29 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20201228_1402'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='committeemembership',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='committeemembership',
            name='committee',
        ),
        migrations.RemoveField(
            model_name='committeemembership',
            name='user',
        ),
        migrations.DeleteModel(
            name='Term',
        ),
        migrations.DeleteModel(
            name='CommitteeMembership',
        ),
    ]
