# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-10-16 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20210828_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='validemaildomain',
            name='hits',
            field=models.PositiveIntegerField(default=0, help_text='Number of emails whose fate was decided by this entry.'),
        ),
        migrations.AlterField(
            model_name='validemaildomain',
            name='status',
            field=models.CharField(choices=[('u', 'Unreviewed'), ('a', 'Accepted'), ('d', 'Denied')], default='a', help_text="Accepted means users may enter with this domain or any subdomain. Denied will disallow submission of requests under this domain or subdomain. The most specific subdomain is used. Unverified is used to automatically add new domains that haven't been seen yet (these are ignored during validation).", max_length=1),
        ),
    ]
