# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-12-29 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20201229_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='index',
            field=models.PositiveSmallIntegerField(default=0, help_text='Order to render on page.'),
        ),
    ]
