# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-11-06 17:14
from __future__ import unicode_literals

from django.db import migrations, models

from members.models import Profile as NewProfile

def update_levels(apps, schema_editor):
    Profile = apps.get_model("members", "Profile")
    LEVELS = {}
    for lvl in NewProfile.LEVELS:
        LEVELS[lvl[1][0:10]] = lvl[0] # We saved only first 10 chars
    for p in Profile.objects.all():
        p.level = LEVELS.get(p.level[0:10], "")
        p.save()

class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20211016_1811'),
    ]

    operations = [

        migrations.RunPython(
            code=update_levels,
        ),
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.CharField(choices=[('0', 'Highschool'), ('1', 'Undergraduate'), ('2', 'Graduate'), ('3', 'PostDoc'), ('4', 'Professor'), ('5', 'Professional'), ('9', 'Retired')], default='2', max_length=2),
        ),
    ]
