# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-12-30 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20201229_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['committee', 'index']},
        ),
        migrations.AlterModelOptions(
            name='positionheld',
            options={'ordering': ['-stop', 'position'], 'verbose_name_plural': 'Positions Held'},
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
    ]
