# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-01-03 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('members', '0008_auto_20201230_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_committee', to='auth.Group')),
            ],
        ),
        migrations.AlterModelOptions(
            name='positionheld',
            options={'ordering': ['-start', 'position'], 'verbose_name_plural': 'Positions Held'},
        ),
    ]
