# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-12-12 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20211106_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscription_requests',
            field=models.ManyToManyField(blank=True, help_text="We do need to manually verify subscriptions, so please bare with us. We are a volunteer organization and we're all grad students too!", related_name='_profile_subscription_requests_+', to='members.EmailList'),
        ),
    ]
