# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-01-03 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_auto_20210103_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(default=django.utils.timezone.localdate)),
                ('stop', models.DateField()),
            ],
            options={
                'ordering': ['-stop'],
            },
        ),
        migrations.AlterField(
            model_name='positionheld',
            name='start',
            field=models.DateField(default=members.models.get_current_term_start),
        ),
    ]
