# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-12-29 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_auto_20211225_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='validemaildomain',
            options={'ordering': ('-hits',)},
        ),
    ]
