# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-01-09 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_auto_20210104_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='contact_email',
            field=models.EmailField(blank=True, help_text="If blank, parent's email will be used if available.", max_length=254),
        ),
        migrations.AddField(
            model_name='committee',
            name='description',
            field=models.TextField(blank=True, help_text='Short description on first line.\n\nLonger description below.\nMultiple lines if needed.', max_length=500),
        ),
        migrations.AddField(
            model_name='committee',
            name='show_email',
            field=models.BooleanField(default=True, help_text='If no self or parent contact_email, will not be displayed.'),
        ),
    ]
