# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-01-09 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_auto_20210109_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='description',
            field=models.TextField(blank=True, help_text='Short description here on first line (next line blank!).<br><br>Elaborate here if you need.<br>Multiple lines if needed.', max_length=500),
        ),
        migrations.AlterField(
            model_name='committee',
            name='show_email',
            field=models.BooleanField(default=True, help_text='If no self or parent Contact email; will not be displayed.'),
        ),
    ]
