# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-01-09 19:53
from __future__ import unicode_literals

from django.db import migrations

def make_missing_committees(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Committee = apps.get_model("members", "Committee")
    for group in Group.objects.filter(committee__isnull=True):
        Committee(group=group).save()

class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_auto_20210109_1421'),
    ]

    operations = [
        migrations.RunPython(make_missing_committees),
    ]
