# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-12-12 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import iquhack.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(unique=True)),
                ('end_date', models.DateField()),
                ('back_drop_image', models.ImageField(upload_to=iquhack.models.upload_backdrop)),
                ('published', models.BooleanField(default=False, help_text='Make available on website.')),
                ('link', models.URLField(blank=True)),
                ('early_note', models.CharField(blank=True, max_length=200)),
                ('opens', models.DateTimeField()),
                ('open_note', models.CharField(blank=True, max_length=200)),
                ('deadline', models.DateTimeField(help_text='THIS WILL NOT PREVENT RESPONSES! Simply removes the link.')),
                ('closed_note', models.CharField(blank=True, max_length=200)),
                ('logo_max_height', models.PositiveSmallIntegerField(default=50, help_text='In pixels.')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, help_text='SVG files strongly encouraged!', upload_to=iquhack.models.upload_sponsor_logo)),
                ('link', models.URLField(blank=True)),
                ('agreement', models.FileField(blank=True, upload_to=iquhack.models.upload_sponsor_agreement)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iquhack.Hackathon')),
            ],
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(default=0, help_text='Higher numbers get rendered lower on page.', unique=True)),
                ('logo_rel_height', models.FloatField(default=100, help_text="Percentage. A value resulting in < 1 pixel won't be rendered.")),
                ('side_margin', models.FloatField(default=12, help_text='Pixels.')),
                ('bottom_margin', models.FloatField(default=8, help_text='Pixels.')),
            ],
        ),
        migrations.AddField(
            model_name='sponsor',
            name='tier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iquhack.Tier'),
        ),
        migrations.AlterUniqueTogether(
            name='sponsor',
            unique_together=set([('hackathon', 'name')]),
        ),
    ]
