# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-12-18 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import iquhack.models


class Migration(migrations.Migration):

    dependencies = [
        ('iquhack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.FileField(blank=True, help_text='SVG files strongly encouraged!', upload_to=iquhack.models.upload_sponsor_logo),
        ),
    ]
