# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-12-13 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [(b'iquhack', '0002_auto_20201213_0920'), (b'iquhack', '0003_auto_20201213_0946')]

    dependencies = [
        ('iquhack', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tier',
            options={'ordering': ['index']},
        ),
        migrations.AddField(
            model_name='sponsor',
            name='platform',
            field=models.BooleanField(default=False, help_text='This sponsor is also providing hardware/platform.'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iquhack.Tier'),
        ),
        migrations.RemoveField(
            model_name='tier',
            name='bottom_margin',
        ),
        migrations.RemoveField(
            model_name='tier',
            name='logo_rel_height',
        ),
        migrations.RemoveField(
            model_name='tier',
            name='side_margin',
        ),
        migrations.AddField(
            model_name='hackathon',
            name='logo_max_bottom_margin',
            field=models.PositiveSmallIntegerField(default=8, help_text='In pixels.'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='logo_max_side_margin',
            field=models.PositiveSmallIntegerField(default=12, help_text='In pixels.'),
        ),
        migrations.AddField(
            model_name='tier',
            name='logo_rel_size',
            field=models.FloatField(default=100, help_text="Percentage. A value resulting in < 1 pixel won't be rendered."),
        ),
    ]
