# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-01-09 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('iquhack', '0002_auto_20201218_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='organizing_committee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
