# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-12-13 16:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import iquhack.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iquhack', '0003_hackathon_organizing_committee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', iquhack.models.JSonField(default='{}', editable=False, help_text='Copy of questions used.')),
                ('responses', iquhack.models.JSonField(default='{}', help_text='JSON encoded.')),
                ('hackathon', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='iquhack.Hackathon')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='iquhack_apps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['hackathon'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defs', iquhack.models.JSonField(default=b'[\n    {\n        "id": "participation_country",\n        "label": "What country do you plan to participate from?",\n        "type": "short"\n    },\n    {\n        "id": "under_18",\n        "label": "Are you under 18?",\n        "help_text": "If selected, we will require guardian contact information.",\n        "type": "radio",\n        "choices": [[true, "Yes"], [false, "No"]]\n    },\n    {\n        "id": "experience",\n        "label": "Please select all the areas that you have had experience in",\n        "type": "multiple",\n        "max_length": null,\n        "choices": [\n            "Quantum Computation",\n            "Quantum Mechanics",\n            "Qiskit, Ocean, or any other quantum programming packages",\n            "Software design or engineering",\n            "Algorithms",\n            "Chemistry",\n            "Visual design",\n            "Basic programming"\n        ]\n    },\n    {\n        "id": "background_detail",\n        "label": "Please tell us a little more about your background",\n        "type": "long",\n        "max_length": 2000\n    },\n    {\n        "id": "interest_detail",\n        "label": "Why are you interested in participating in iQuHACK?",\n        "type": "long",\n        "max_length": 2000\n    },\n    {\n        "id": "how_heard",\n        "label": "How did you hear about iQuHACK?",\n        "type": "multiple",\n        "max_length": null,\n        "choices": [\n            "Website",\n            "Email",\n            "Facebook",\n            "Twitter",\n            "LinkedIn",\n            "News article",\n            "I participated last year"\n        ],\n        "required": false\n    }\n]', help_text='JSON encoded.')),
            ],
        ),
        migrations.AddField(
            model_name='hackathon',
            name='app_questions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='iquhack.ApplicationQuestions'),
        ),
    ]
