# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-12-15 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iquhack', '0004_auto_20201215_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='general',
            field=models.BooleanField(default=True, help_text="Check this if this question and answer pair are general enough for any hackathon. If unchecked, it won't be listed in the hackathon's list of available FAQs."),
        ),
    ]
