# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-12-14 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import iquhack.models


class Migration(migrations.Migration):

    dependencies = [
        ('iquhack', '0004_auto_20211213_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='questions',
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='app_questions',
            field=iquhack.models.JSonField(default=b'[\n    {\n        "id": "participation_country",\n        "label": "What country do you plan to participate from?",\n        "type": "short"\n    },\n    {\n        "id": "under_18",\n        "label": "Are you under 18?",\n        "help_text": "If selected, we will require guardian contact information.",\n        "type": "radio",\n        "choices": [[true, "Yes"], [false, "No"]]\n    },\n    {\n        "id": "experience",\n        "label": "Please select all the areas that you have had experience in",\n        "type": "multiple",\n        "max_length": null,\n        "choices": [\n            "Quantum Computation",\n            "Quantum Mechanics",\n            "Qiskit, Ocean, or any other quantum programming packages",\n            "Software design or engineering",\n            "Algorithms",\n            "Chemistry",\n            "Visual design",\n            "Basic programming"\n        ]\n    },\n    {\n        "id": "background_detail",\n        "label": "Please tell us a little more about your background",\n        "type": "long",\n        "max_length": 2000\n    },\n    {\n        "id": "interest_detail",\n        "label": "Why are you interested in participating in iQuHACK?",\n        "type": "long",\n        "max_length": 2000\n    },\n    {\n        "id": "how_heard",\n        "label": "How did you hear about iQuHACK?",\n        "type": "multiple",\n        "max_length": null,\n        "choices": [\n            "Website",\n            "Email",\n            "Facebook",\n            "Twitter",\n            "LinkedIn",\n            "News article",\n            "I participated last year"\n        ],\n        "required": false\n    }\n]', help_text='JSON encoded.'),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='deadline',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='link',
            field=models.URLField(blank=True, help_text='DEPRECATED'),
        ),
        migrations.DeleteModel(
            name='ApplicationQuestions',
        ),
    ]
