# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-12-15 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iquhack', '0005_section_general'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(help_text="This must be HTML! You can use the Django template language.<br>The following context will be available:<br>&nbsp;&nbsp;&nbsp;&nbsp;hackathon: The Hackathon database object.<br>&nbsp;&nbsp;&nbsp;&nbsp;formatted_event_date: The event's date formatted like 'February 1st-2nd'<br>", max_length=1000),
        ),
        migrations.AlterField(
            model_name='section',
            name='content',
            field=models.TextField(help_text="This must be HTML! You can use the Django template language.<br>The following context will be available:<br>&nbsp;&nbsp;&nbsp;&nbsp;hackathon: The Hackathon database object.<br>&nbsp;&nbsp;&nbsp;&nbsp;formatted_event_date: The event's date formatted like 'February 1st-2nd'<br>", max_length=1000),
        ),
        migrations.AlterField(
            model_name='section',
            name='general',
            field=models.BooleanField(default=True, help_text="Check this if this question and answer pair are general enough for any hackathon. If unchecked, it won't be listed in the hackathon's list of available sections."),
        ),
    ]
