# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-12-16 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iquhack', '0006_auto_20201215_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=100),
        ),
    ]
