# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-12-26 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iquhack', '0006_auto_20211225_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='consent',
            field=models.BooleanField(default=False),
        ),
    ]
