# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-12-18 01:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import iquhack.models


class Migration(migrations.Migration):

    dependencies = [
        ('iquhack', '0007_auto_20201216_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='If empty, will use filename without the extension.', max_length=50)),
                ('file', models.FileField(upload_to=iquhack.models.upload_section_attachment)),
            ],
        ),
        migrations.CreateModel(
            name='SectionTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('content', models.TextField(help_text="This must be HTML! You can use the Django template language.<br>The following context will be available:<br>&nbsp;&nbsp;&nbsp;&nbsp;hackathon: The Hackathon database object.<br>&nbsp;&nbsp;&nbsp;&nbsp;formatted_event_date: The event's date formatted like 'February 1st-2nd'<br>", max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='usedsection',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='usedsection',
            name='hackathon',
        ),
        migrations.RemoveField(
            model_name='usedsection',
            name='section',
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['index']},
        ),
        migrations.RemoveField(
            model_name='hackathon',
            name='sections',
        ),
        migrations.AddField(
            model_name='section',
            name='hackathon',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='iquhack.Hackathon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='index',
            field=models.PositiveSmallIntegerField(default=0, help_text='Higher numbers get rendered lower on page.'),
        ),
        migrations.AlterField(
            model_name='section',
            name='content',
            field=models.TextField(help_text="This must be HTML! You can use the Django template language.<br>The following context will be available:<br>&nbsp;&nbsp;&nbsp;&nbsp;hackathon: The Hackathon database object.<br>&nbsp;&nbsp;&nbsp;&nbsp;formatted_event_date: The event's date formatted like 'February 1st-2nd'<br><br><br>Additionally, this can implement sections defined in the template if provided.<br>Files can be accessed using {{ attachments | get_item: '[NAME]' }}", max_length=1000),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.RemoveField(
            model_name='section',
            name='general',
        ),
        migrations.AddField(
            model_name='section',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iquhack.SectionTemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set([('hackathon', 'index'), ('hackathon', 'title')]),
        ),
        migrations.DeleteModel(
            name='UsedSection',
        ),
        migrations.AddField(
            model_name='attachment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iquhack.Section'),
        ),
        migrations.AlterUniqueTogether(
            name='attachment',
            unique_together=set([('section', 'name')]),
        ),
    ]
