# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-12-18 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iquhack', '0008_auto_20201217_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='content',
            field=models.TextField(blank=True, help_text="This must be HTML! You can use the Django template language.<br>The following context will be available:<br>&nbsp;&nbsp;&nbsp;&nbsp;hackathon: The Hackathon database object.<br>&nbsp;&nbsp;&nbsp;&nbsp;formatted_event_date: The event's date formatted like 'February 1st-2nd'<br><br><br>Additionally, this can implement sections defined in the template if provided.<br>Files can be accessed using {{ attachments |get_item:'[NAME]' }} (careful with spaces)."),
        ),
        migrations.AlterField(
            model_name='sectiontemplate',
            name='content',
            field=models.TextField(help_text="This must be HTML! You can use the Django template language.<br>The following context will be available:<br>&nbsp;&nbsp;&nbsp;&nbsp;hackathon: The Hackathon database object.<br>&nbsp;&nbsp;&nbsp;&nbsp;formatted_event_date: The event's date formatted like 'February 1st-2nd'<br>"),
        ),
    ]
