# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2022-01-23 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iquhack', '0008_auto_20211229_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['hackathon', '-accepted']},
        ),
        migrations.AddField(
            model_name='section',
            name='restricted',
            field=models.BooleanField(default=False, help_text='Only display to staff and accepted participants.'),
        ),
    ]
