# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-12-18 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iquhack', '0009_auto_20201217_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='general',
            field=models.BooleanField(default=False, help_text="Check this if this question and answer pair are general enough for any hackathon. If unchecked, it won't be listed in the hackathon's list of available FAQs."),
        ),
        migrations.AlterField(
            model_name='usedfaq',
            name='index',
            field=models.PositiveSmallIntegerField(default=0, help_text='Higher numbers get rendered lower on page.'),
        ),
        migrations.AlterUniqueTogether(
            name='usedfaq',
            unique_together=set([('hackathon', 'FAQ'), ('hackathon', 'index')]),
        ),
    ]
