# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2022-01-25 02:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iquhack', '0009_auto_20220123_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mask_size',
            field=models.CharField(choices=[[0, 'YS/M'], [1, 'YL/XL'], [2, 'S/M'], [3, 'L/XL'], [4, 'N/A']], default=2, help_text="<a href='https://drive.google.com/file/d/1SiGfo68-teoHFz0xOZAi05rRRfkSOqIR/view?usp=sharing'>Sizing Chart</a>", max_length=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='pick_up',
            field=models.BooleanField(default=False, help_text='You can pick up your swag at MIT instead of us shipping it.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='shirt_size',
            field=models.CharField(choices=[[0, 'XS'], [1, 'S'], [2, 'M'], [3, 'L'], [4, 'XL'], [5, 'XXL'], [6, 'XXXL'], [7, 'N/A']], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='shipping_address',
            field=models.ForeignKey(blank=True, help_text='We use this to ship you your swag.', null=True, on_delete=django.db.models.deletion.PROTECT, to='iquhack.Address'),
        ),
        migrations.AlterField(
            model_name='section',
            name='restricted',
            field=models.BooleanField(default=False, help_text='Only display to staff and accepted/consented participants while hackathon is running.'),
        ),
    ]
